name: Lint and Build (PR)

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dev-env/Dockerfile

  build:
    name: Build Image
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Attempt checkout of docs-cache branch (optional)
        id: docs_cache
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: docs-cache
          path: docs-cache

      - name: Sync docs into workspace if present
        if: steps.docs_cache.outcome == 'success'
        run: rsync -a --delete docs-cache/docs ./docs || echo "No cached docs to sync"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1
        with:
          context: .
          file: ./dev-env/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
