name: Publish dev-env image

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Attempt checkout of docs-cache branch (optional)
        id: docs_cache
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: docs-cache
          path: docs-cache

      - name: Sync docs into workspace if present
        if: steps.docs_cache.outcome == 'success'
        run: rsync -a --delete docs-cache/docs ./docs || echo "No cached docs to sync"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@v1
        with:
          context: .
          file: ./dev-env/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Docker layer caching handled automatically by Blacksmith